# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pyinstaller
    - name: Install pyevilemu
      run: |
        git clone https://github.com/daid/pyevilemu.git
        cd pyevilemu
        python setup.py install
    - name: Build with pyinstaller
      run: |
        cd viewervivify
        pyinstaller --clean -y main.py
        zip 
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v3
      with:
        name: windows-dist
        path: viewervivify/dist/windows
